class Emojis:
    """Classe para centralizar emojis utilizados na aplicação"""
    
    # Símbolos gerais
    CHECK = "✅"
    CROSS = "❌"
    WARNING = "⚠️"
    INFO = "ℹ️"
    STAR = "⭐"
    FIRE = "🔥"
    ROCKET = "🚀"
    SPARKLES = "✨"
    ZAP = "⚡"
    BOOM = "💥"
    EYES = "👀"
    THINKING = "🤔"
    WAVE = "👋"
    POINT_RIGHT = "👉"
    POINT_LEFT = "👈"
    
    # Setas
    ARROW_RIGHT = "→"
    ARROW_LEFT = "←"
    ARROW_UP = "↑"
    ARROW_DOWN = "↓"
    ARROW_RIGHT_EMOJI = "➡️"
    ARROW_LEFT_EMOJI = "⬅️"
    ARROW_UP_EMOJI = "⬆️"
    ARROW_DOWN_EMOJI = "⬇️"
    BACK = "🔙"
    SOON = "🔜"
    
    # Tecnologia
    COMPUTER = "💻"
    GEAR = "⚙️"
    LOCK = "🔒"
    UNLOCK = "🔓"
    KEY = "🔑"
    CHART = "📊"
    DOCUMENT = "📄"
    FOLDER = "📁"
    DATABASE = "🗄️"
    SERVER = "🖥️"
    MOBILE = "📱"
    LINK = "🔗"
    BROKEN_LINK = "⛓️‍💥"
    CODE = "💻"
    BUG = "🐛"
    WRENCH = "🔧"
    HAMMER = "🔨"
    NUT_AND_BOLT = "🔩"
    MAGNET = "🧲"
    SATELLITE = "🛰️"
    BATTERY = "🔋"
    PLUG = "🔌"
    
    # Ações
    SEARCH = "🔍"
    EDIT = "✏️"
    DELETE = "🗑️"
    SAVE = "💾"
    DOWNLOAD = "⬇️"
    UPLOAD = "⬆️"
    REFRESH = "🔄"
    SYNC = "🔁"
    PLAY = "▶️"
    PAUSE = "⏸️"
    STOP = "⏹️"
    FAST_FORWARD = "⏩"
    REWIND = "⏪"
    COPY = "📋"
    CUT = "✂️"
    PLUS = "➕"
    MINUS = "➖"
    MULTIPLY = "✖️"
    DIVIDE = "➗"
    
    # Status
    SUCCESS = "✔️"
    ERROR = "❗"
    LOADING = "⏳"
    CLOCK = "🕐"
    HOURGLASS = "⌛"
    ALARM = "⏰"
    TIMER = "⏲️"
    CALENDAR = "📅"
    CONSTRUCTION = "🚧"
    NO_ENTRY = "⛔"
    PROHIBITED = "🚫"
    
    # Comunicação
    EMAIL = "📧"
    BELL = "🔔"
    MESSAGE = "💬"
    SPEECH_BALLOON = "💭"
    LOUDSPEAKER = "📢"
    MEGAPHONE = "📣"
    INBOX = "📥"
    OUTBOX = "📤"
    PACKAGE = "📦"
    
    # Números
    ONE = "1️⃣"
    TWO = "2️⃣"
    THREE = "3️⃣"
    FOUR = "4️⃣"
    FIVE = "5️⃣"
    SIX = "6️⃣"
    SEVEN = "7️⃣"
    EIGHT = "8️⃣"
    NINE = "9️⃣"
    ZERO = "0️⃣"
    TEN = "🔟"
    
    # Bandeiras
    FLAG_BR = "🇧🇷"
    FLAG_US = "🇺🇸"
    FLAG_UK = "🇬🇧"
    CHECKERED_FLAG = "🏁"
    WHITE_FLAG = "🏳️"
    RAINBOW_FLAG = "🏳️‍🌈"
    
    # Mãos e gestos
    THUMBS_UP = "👍"
    THUMBS_DOWN = "👎"
    OK_HAND = "👌"
    CLAP = "👏"
    RAISED_HAND = "✋"
    FIST = "✊"
    VICTORY = "✌️"
    MUSCLE = "💪"
    PRAY = "🙏"
    
    # Emoções
    SMILE = "😊"
    HAPPY = "😄"
    LAUGH = "😂"
    LOVE = "😍"
    HEART_EYES = "😍"
    COOL = "😎"
    WINK = "😉"
    CONFUSED = "😕"
    SAD = "😢"
    ANGRY = "😠"
    SURPRISED = "😮"
    TIRED = "😴"
    
    # Corações
    RED_HEART = "❤️"
    ORANGE_HEART = "🧡"
    YELLOW_HEART = "💛"
    GREEN_HEART = "💚"
    BLUE_HEART = "💙"
    PURPLE_HEART = "💜"
    BLACK_HEART = "🖤"
    WHITE_HEART = "🤍"
    BROKEN_HEART = "💔"
    HEART = "♥️"
    
    # Natureza
    SUN = "☀️"
    MOON = "🌙"
    CLOUD = "☁️"
    RAIN = "🌧️"
    SNOW = "❄️"
    TREE = "🌲"
    FLOWER = "🌸"
    LEAF = "🍃"
    EARTH = "🌍"
    GLOBE = "🌐"
    
    # Objetos
    LIGHT_BULB = "💡"
    TROPHY = "🏆"
    TARGET = "🎯"
    PARTY = "🎉"
    GIFT = "🎁"
    BALLOON = "🎈"
    MEDAL = "🏅"
    CROWN = "👑"
    GEM = "💎"
    MONEY = "💰"
    DOLLAR = "💵"
    CREDIT_CARD = "💳"
    BRIEFCASE = "💼"
    CLIPBOARD = "📋"
    BOOKMARK = "🔖"
    LABEL = "🏷️"
    PAPERCLIP = "📎"
    PIN = "📌"
    SCISSORS = "✂️"
    PEN = "🖊️"
    PENCIL = "✏️"
    PAINTBRUSH = "🖌️"
    BOOK = "📖"
    BOOKS = "📚"
    NOTEBOOK = "📓"
    NEWSPAPER = "📰"
    
    # Comida e bebida
    COFFEE = "☕"
    TEA = "🍵"
    BEER = "🍺"
    WINE = "🍷"
    COCKTAIL = "🍹"
    PIZZA = "🍕"
    BURGER = "🍔"
    CAKE = "🎂"
    COOKIE = "🍪"
    CANDY = "🍬"
    APPLE = "🍎"
    BANANA = "🍌"
    
    # Transporte
    CAR = "🚗"
    BUS = "🚌"
    TRAIN = "🚆"
    AIRPLANE = "✈️"
    BIKE = "🚲"
    SHIP = "🚢"
    
    # Outros
    RAINBOW = "🌈"
    DIAMOND = "💠"
    CIRCLE = "⭕"
    SQUARE = "⬛"
    TRIANGLE = "🔺"
    QUESTION = "❓"
    EXCLAMATION = "❕"
    DOUBLE_EXCLAMATION = "‼️"
    QUESTION_EXCLAMATION = "⁉️"
    INFINITY = "♾️"
    RECYCLE = "♻️"
    COPYRIGHT = "©️"
    REGISTERED = "®️"
    TRADEMARK = "™️"
